### ISSUE TITLE
Playground: Back to home button goes back, not to home

### ISSUE THREAD

**Issue by ericvicenti** [rise-tools/rise-tools#203]
The "Back to Home" button will take you home if this is the only connection you have open.

But if you scan several connection QRCodes, the "Back to Home" button will not take you home, it will just close the current connection

**Comment by grabbou** [comment]
Maybe opening QR Code should always replace, not push, a new connection screen? Otherwise, you end up having and being subscribed to two connections.

That way, going back would still go back to the Home Screen. 

We can change go back to 'go to the root', but it does not make sense to have two open web socket connections even though you're just seeing one on screen, with no way of going back.

**Comment by ericvicenti** [comment]
yes I agree. But it should reset, not replace. Because replace will only replace the last route in the stack, and you may have several dynamic routes open from the other connection

**Comment by grabbou** [comment]
Makes sense, I have playground open for some other work right now, will send an update!

**Comment by grabbou** [comment]
Fixed
